Repository PowerDNS-Admin/PowerDNS-Admin, pull requests merged in 2022-12, with the labels that each got.

#1298 Added current wiki content to project files.
  docs/wiki/Configure-Active-Directory-Authentication-using-Group-Security.md
  docs/wiki/DynDNS2.md
  docs/wiki/Home.md
  docs/wiki/Install-PowerDNS-Admin-in-Fedora-23.md
  docs/wiki/Prepare-MySQL-or-MariaDB-Database-for-PowerDNS-Admin.md
  docs/wiki/Running-PowerDNS-Admin-as-a-service-(Systemd).md
  docs/wiki/Running-PowerDNS-Admin-on-Centos-7.md
  docs/wiki/Running-PowerDNS-Admin-on-Fedora-30.md
  docs/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian.md
  docs/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx.md
  docs/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn-and-Apache.md
  docs/wiki/Running-on-FreeBSD.md
  docs/wiki/Supervisord-example.md
  docs/wiki/Systemd-example.md
  docs/wiki/Using-PowerDNS-Admin-with-PostgreSQL.md
  docs/wiki/WSGI-Apache-example.md
  docs/wiki/images/readme_screenshots/fullscreen-dashboard.png
  docs/wiki/images/readme_screenshots/fullscreen-domaincreate.png
  docs/wiki/images/readme_screenshots/fullscreen-domainmanage.png
  docs/wiki/images/readme_screenshots/fullscreen-login.png
  docs/wiki/images/webui/create.jpg
  docs/wiki/images/webui/index.jpg
  docs/wiki/images/webui/login.jpg
  docs/wiki/uWSGI-example.md
Labels: enhancement

#1299 Setup new wiki docs #1
  docs/wiki/Home.md
  docs/wiki/Install-PowerDNS-Admin-in-Fedora-23.md
  docs/wiki/README.md
  docs/wiki/Running-PowerDNS-Admin-as-a-service-(Systemd).md
  docs/wiki/features/DynDNS2.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Centos-7.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Fedora-23.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Fedora-30.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Ubuntu-or-Debian.md
  docs/wiki/install/Running-on-FreeBSD.md
  docs/wiki/preparation/Prepare-MySQL-or-MariaDB-Database-for-PowerDNS-Admin.md
  docs/wiki/preparation/Using-PowerDNS-Admin-with-PostgreSQL.md
  docs/wiki/web-server/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx.md
  docs/wiki/web-server/Running-PowerDNS-Admin-with-Systemd,-Gunicorn-and-Apache.md
  docs/wiki/web-server/Supervisord-example.md
  docs/wiki/web-server/Systemd-example.md
  docs/wiki/web-server/WSGI-Apache-example.md
  docs/wiki/web-server/uWSGI-example.md
Labels: enhancement

#1301 enhancement: Small fix
  powerdnsadmin/models/api_key.py
Labels: python, api

#1247 models/user.py: properly guard plain_text_password property
  powerdnsadmin/models/user.py
Labels: bug, authentication

#1246 admin_edit_key: default to User role for new api keys
  powerdnsadmin/templates/admin_edit_key.html
Labels: accepted, reviewed

#1242 Update to python-ldap 3.4.2
  requirements.txt
Labels: bug, deployment

#1310 Fix PostgreSQL documentation
  docs/wiki/database-setup/Setup-MySQL-or-MariaDB.md
  docs/wiki/database-setup/Setup-PostgreSQL.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Centos-7.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Fedora-30.md
Labels: documentation

#1312 Working on updated workflow for Docker image publishing.
  .github/workflows/build-and-publish.yml
  docker/Dockerfile
Labels: docker

#1315 Updated Docker Image Publishing Workflow
  .github/workflows/build-and-publish.yml
Labels: docker

#1316 Docker Image Repository References Updated
  README.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Docker.md
Labels: documentation, docker

#1324 fix of issue #1261 & #1321
  deploy/kubernetes/deployment.yml
  docker-compose.yml
  powerdnsadmin/lib/utils.py
Labels: bug

#1327 Docs updates
  docs/wiki/README.md
  docs/wiki/configuration/Environment-variables.md
  docs/wiki/database-setup/Setup-MySQL-or-MariaDB.md
  docs/wiki/database-setup/Setup-PostgreSQL.md
  docs/wiki/install/Architecture.png
  docs/wiki/install/General.md
Labels: documentation

#1330 Fix #1329
  powerdnsadmin/models/user.py
Labels: bug

#1322 Fixing Validation problem on LDAP form
  powerdnsadmin/templates/admin_setting_authentication.html
Labels: bug, javascript, ui

#1331 enhancement(routes/index.py): OIDC supports HTTP Scheme now
  powerdnsadmin/routes/index.py
Labels: enhancement

#1332 Revert "enhancement(routes/index.py): OIDC supports HTTP Scheme now"
  powerdnsadmin/routes/index.py
Labels: bug, docker

#1333 enhancement: Added 2 new files (auto-setup)
  deploy/auto-setup/setup_linux.sh
  deploy/auto-setup/setup_win.bat
Labels: enhancement
