Repository PowerDNS-Admin/PowerDNS-Admin, pull requests merged in 2022-06, with the labels that each got.

#1163 Idna decode
  powerdnsadmin/lib/utils.py
  powerdnsadmin/models/record.py
  powerdnsadmin/routes/domain.py
Labels: bug, accepted, reviewed

#1206 feat: Add /api endpoint
  powerdnsadmin/routes/__init__.py
  powerdnsadmin/routes/api.py
Labels: api, accepted

#1214 Fix DynDNS2 using X-Forwarded-For
  powerdnsadmin/routes/index.py
Labels: bug, accepted

#1205 Modification to SAML groups and group management
  configs/development.py
  powerdnsadmin/routes/index.py
Labels: stale, authentication, user management

#1089 Enforce Record Restrictions in API
  powerdnsadmin/decorators.py
  powerdnsadmin/lib/errors.py
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/api.py
Labels: api, accepted, reviewed

#1218 Improve performance of domain update
  powerdnsadmin/models/domain.py
Labels: enhancement, python, accepted, reviewed

#1047 feat: Allow underscores and hyphens in account name
  powerdnsadmin/lib/errors.py
  powerdnsadmin/models/account.py
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/api.py
  powerdnsadmin/routes/index.py
  powerdnsadmin/templates/admin_edit_account.html
Labels: enhancement, feature request, python

#1201 Update zone using a single api call
  powerdnsadmin/models/record.py
Labels: api, accepted, changes requested, reviewed

#1211 Fix cookie config
  configs/docker_config.py
  powerdnsadmin/__init__.py
  powerdnsadmin/default_config.py
  powerdnsadmin/routes/__init__.py
  powerdnsadmin/routes/api.py
  powerdnsadmin/routes/base.py
  powerdnsadmin/routes/index.py
  requirements.txt
Labels: bug, accepted, changes requested, reviewed

#1227 Allow new domains to be absolute
  powerdnsadmin/routes/domain.py
Labels: python, accepted
