Repository PowerDNS-Admin/PowerDNS-Admin, pull requests merged in 2023-02, with the labels that each got.

#1231 Allow to manage associated domains under account edit
  powerdnsadmin/models/domain.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/templates/admin_edit_account.html
Labels: mod / accepted, feature / update

#1248 routes/index.py: otp_force shouldn't apply to OAuth
  powerdnsadmin/routes/index.py
Labels: bug / broken-feature

#1381 Domain records list performance improvement - removing Setting.get query from loop
  powerdnsadmin/routes/domain.py
Labels: mod / accepted, feature / update

#1380 Preserve domain records history after domain deletion
  powerdnsadmin/models/domain.py
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
Labels: mod / accepted, feature / update

#1374 Changed auto_ptr() logic to remove-then-add
  powerdnsadmin/models/record.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1078 fix: making the key name in the config database unique
  migrations/versions/b24bf17725d2_add_unique_index_to_settings_table_keys.py
  powerdnsadmin/models/setting.py
Labels: skill / database, mod / accepted, mod / reviewed

#1371 [WIP] Admin LTE & Bootstrap Upgrade
  configs/development.py
  package.json
  powerdnsadmin/assets.py
  powerdnsadmin/routes/__init__.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/base.py
  powerdnsadmin/routes/index.py
  powerdnsadmin/static/custom/js/custom.js
  powerdnsadmin/templates/admin_edit_account.html
  powerdnsadmin/templates/admin_edit_key.html
  powerdnsadmin/templates/admin_edit_user.html
  powerdnsadmin/templates/admin_global_search.html
  powerdnsadmin/templates/admin_history.html
  powerdnsadmin/templates/admin_history_table.html
  powerdnsadmin/templates/admin_manage_account.html
  powerdnsadmin/templates/admin_manage_keys.html
  powerdnsadmin/templates/admin_manage_user.html
  powerdnsadmin/templates/admin_pdns_stats.html
  powerdnsadmin/templates/admin_setting_authentication.html
  powerdnsadmin/templates/admin_setting_basic.html
  powerdnsadmin/templates/admin_setting_pdns.html
  powerdnsadmin/templates/admin_setting_records.html
  powerdnsadmin/templates/base.html
  powerdnsadmin/templates/dashboard.html
  powerdnsadmin/templates/dashboard_domain.html
  powerdnsadmin/templates/domain.html
  powerdnsadmin/templates/domain_add.html
  powerdnsadmin/templates/domain_changelog.html
  powerdnsadmin/templates/domain_remove.html
  powerdnsadmin/templates/domain_setting.html
  powerdnsadmin/templates/errors/400.html
  powerdnsadmin/templates/errors/403.html
  powerdnsadmin/templates/errors/404.html
  powerdnsadmin/templates/errors/500.html
  powerdnsadmin/templates/errors/SAML.html
  powerdnsadmin/templates/login.html
  powerdnsadmin/templates/register.html
  powerdnsadmin/templates/register_otp.html
  powerdnsadmin/templates/template.html
  powerdnsadmin/templates/template_add.html
  powerdnsadmin/templates/template_edit.html
  powerdnsadmin/templates/user_profile.html
  requirements.txt
  yarn.lock
Labels: mod / accepted, mod / reviewed, feature / dependency, feature / update

#1393 fix: configurable CAPTCHA_ENABLE env when docker use
  configs/docker_config.py
Labels: mod / accepted, mod / reviewed, feature / update

#1377 API record change history format fix
  powerdnsadmin/routes/api.py
Labels: mod / changes-requested, mod / reviewed, feature / update

#1392 Issue 1391 - Feature: Mobile First Responsive UI Design
  powerdnsadmin/__init__.py
  powerdnsadmin/lib/utils.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/static/custom/css/custom.css
  powerdnsadmin/static/custom/js/custom.js
  powerdnsadmin/templates/admin_edit_account.html
  powerdnsadmin/templates/admin_edit_key.html
  powerdnsadmin/templates/admin_edit_user.html
  powerdnsadmin/templates/admin_global_search.html
  powerdnsadmin/templates/admin_history.html
  powerdnsadmin/templates/admin_manage_account.html
  powerdnsadmin/templates/admin_manage_keys.html
  powerdnsadmin/templates/admin_manage_user.html
  powerdnsadmin/templates/admin_pdns_stats.html
  powerdnsadmin/templates/admin_server_configuration.html
  powerdnsadmin/templates/admin_server_statistics.html
  powerdnsadmin/templates/admin_setting_authentication.html
  powerdnsadmin/templates/admin_setting_basic.html
  powerdnsadmin/templates/admin_setting_pdns.html
  powerdnsadmin/templates/admin_setting_records.html
  powerdnsadmin/templates/base.html
  powerdnsadmin/templates/dashboard.html
  powerdnsadmin/templates/dashboard_domain.html
  powerdnsadmin/templates/domain.html
  powerdnsadmin/templates/domain_add.html
  powerdnsadmin/templates/domain_remove.html
  powerdnsadmin/templates/domain_setting.html
  powerdnsadmin/templates/email_confirmation.html
  powerdnsadmin/templates/emails/account_verification.html
  powerdnsadmin/templates/errors/400.html
  powerdnsadmin/templates/errors/403.html
  powerdnsadmin/templates/errors/404.html
  powerdnsadmin/templates/errors/500.html
  powerdnsadmin/templates/errors/SAML.html
  powerdnsadmin/templates/login.html
  powerdnsadmin/templates/maintenance.html
  powerdnsadmin/templates/register.html
  powerdnsadmin/templates/register_otp.html
  powerdnsadmin/templates/resend_confirmation_email.html
  powerdnsadmin/templates/template.html
  powerdnsadmin/templates/template_add.html
  powerdnsadmin/templates/template_edit.html
  powerdnsadmin/templates/user_profile.html
Labels: feature / request, skill / javascript, skill / python, skill / html, feature / update

#1397 Add support for oidc_oauth_metadata_url configuration option
  configs/docker_config.py
  docs/oauth.md
  docs/wiki/configuration/Environment-variables.md
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/services/oidc.py
  powerdnsadmin/templates/admin_setting_authentication.html
Labels: feature / update

#1398 Update domain_setting.html
  powerdnsadmin/templates/domain_setting.html
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1335 Add OIDC env vars and set SAML_ENABLED as False if unset
  configs/docker_config.py
  powerdnsadmin/routes/index.py
Labels: feature / request, mod / accepted, mod / reviewed
