Repository PowerDNS-Admin/PowerDNS-Admin, pull requests merged in 2023-04, with the labels that each got.

#1500 OAuth Settings Updates
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/services/azure.py
  powerdnsadmin/services/github.py
  powerdnsadmin/services/google.py
  powerdnsadmin/services/oidc.py
  powerdnsadmin/templates/admin_setting_authentication.html
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1502 Fix Zone Type can not be changed from "native" when adding or modifying zones
  powerdnsadmin/routes/domain.py
  powerdnsadmin/templates/domain_add.html
  powerdnsadmin/templates/domain_setting.html
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1515 Feature Update: OAuth Settings Management / Dual-Schema Support
  configs/docker_config.py
  docs/wiki/configuration/Environment-variables.md
  package.json
  powerdnsadmin/assets.py
  powerdnsadmin/default_config.py
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/index.py
  powerdnsadmin/services/azure.py
  powerdnsadmin/services/github.py
  powerdnsadmin/services/google.py
  powerdnsadmin/services/oidc.py
  powerdnsadmin/static/custom/js/app-authentication-settings-editor.js
  powerdnsadmin/templates/admin_setting_authentication.html
  powerdnsadmin/templates/base.html
  yarn.lock
Labels: mod / accepted, mod / reviewed, feature / update

#1504 Show the current zone type and soa-edit-api settings on the zone settings page
  powerdnsadmin/routes/domain.py
  powerdnsadmin/templates/domain_setting.html
Labels: mod / accepted, mod / reviewed, feature / update

#1491 Feature Update: Allow more than 100 rows in the zone list view.
  powerdnsadmin/routes/dashboard.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1507 Zone rrset changelog display improvement
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/domain.py
  powerdnsadmin/templates/admin_history_table.html
  powerdnsadmin/templates/applied_change_macro.html
  powerdnsadmin/templates/domain_changelog.html
Labels: mod / accepted, mod / reviewed, feature / update

#1520 Added support for building `ARM` and `ARM64` based Docker images.
  .github/workflows/build-and-publish.yml
Labels: feature / request, mod / accepted, mod / reviewed

#1522 Updated default value of `SERVER_EXTERNAL_SSL` environment setting
  configs/development.py
  configs/docker_config.py
  powerdnsadmin/default_config.py
Labels: mod / accepted, mod / reviewed, feature / update

#1527 Updated the OAuth service providers to properly respect the new OAuth auto-configuration settings for each provider.
  powerdnsadmin/services/azure.py
  powerdnsadmin/services/github.py
  powerdnsadmin/services/google.py
  powerdnsadmin/services/oidc.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1529 Corrected issue with `SERVER_EXTERNAL_SSL` setting not being extracted from the app's environment.
  configs/development.py
  configs/docker_config.py
  powerdnsadmin/default_config.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1530 Fixed issue with all unassigned zones being selected after a new account's name fails to validate
  powerdnsadmin/templates/admin_edit_account.html
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1535 Allow all application settings to be configured by environment variables
  configs/docker_config.py
  powerdnsadmin/__init__.py
  powerdnsadmin/decorators.py
  powerdnsadmin/default_config.py
  powerdnsadmin/lib/settings.py
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/domain.py
Labels: mod / accepted, mod / reviewed, feature / update

#1537 Fix record comment removal
  powerdnsadmin/models/record.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1549 Automatically focus username field in login view
  powerdnsadmin/templates/login.html
Labels: mod / accepted, mod / reviewed, feature / update
