Repository PowerDNS-Admin/PowerDNS-Admin, pull requests merged in 2023-03, with the labels that each got.

#1416 Standard user domain records list performance loop improvement
  powerdnsadmin/routes/domain.py
  powerdnsadmin/templates/domain.html
Labels: mod / accepted, mod / reviewed, feature / update

#1379 Fix dashboard MySQL performance with large history for standard users
  powerdnsadmin/routes/dashboard.py
Labels: mod / accepted, mod / reviewed, feature / update

#1378 Global Search available for all users
  powerdnsadmin/routes/admin.py
  powerdnsadmin/templates/base.html
Labels: mod / accepted, mod / reviewed, feature / update

#1420 Fixed scrolling on long content
  powerdnsadmin/templates/domain.html
Labels: mod / accepted, mod / reviewed, feature / update

#1421 Sort records label-wise right to left
  powerdnsadmin/templates/domain.html
Labels: mod / accepted, mod / reviewed, feature / update

#1423 Diff-ify changelog view for zone changes
  powerdnsadmin/routes/admin.py
  powerdnsadmin/static/custom/css/custom.css
  powerdnsadmin/templates/admin_history.html
  powerdnsadmin/templates/applied_change_macro.html
Labels: mod / accepted, mod / reviewed, feature / update

#1422 Clean up dashboard zone tabs
  powerdnsadmin/lib/utils.py
  powerdnsadmin/routes/dashboard.py
  powerdnsadmin/templates/dashboard.html
Labels: mod / accepted, mod / reviewed, feature / update

#1432 Feature: Added new JWKS URL setting for each OAuth provider
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/services/azure.py
  powerdnsadmin/services/github.py
  powerdnsadmin/services/google.py
  powerdnsadmin/services/oidc.py
  powerdnsadmin/templates/admin_setting_authentication.html
Labels: feature / update

#1436 Feature: Add OAuth Setting for Server Metadata URL
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/services/azure.py
  powerdnsadmin/services/github.py
  powerdnsadmin/services/google.py
  powerdnsadmin/templates/admin_setting_authentication.html
Labels: feature / update

#1440 Added custom header to be used in the created_by column.
  docs/wiki/configuration/basic_settings.md
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/api.py
Labels: mod / changes-requested, feature / update

#1451 Upgrade lxml & python3-saml dependencies with workaround
  requirements.txt
Labels: mod / accepted, mod / reviewed, feature / dependency

#1452 Fix user confirmed column migration issue
  migrations/versions/3f76448bb6de_add_user_confirmed_column.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed, feature / update

#1453 Basic Auth Exception Handling Improvement
  powerdnsadmin/decorators.py
Labels: mod / accepted, mod / reviewed, feature / update

#1434 PostgreSQL Support Improvement
  configs/development.py
  docker-test/Dockerfile
  docker/Dockerfile
  docs/wiki/database-setup/Setup-PostgreSQL.md
  docs/wiki/install/Running-PowerDNS-Admin-on-Ubuntu-or-Debian.md
  requirements.txt
Labels: mod / accepted, mod / reviewed, feature / dependency, feature / update

#1454 Basic Auth Exception Handling Improvement Update
  powerdnsadmin/routes/base.py
Labels: mod / accepted, mod / reviewed, feature / update

#1457 Implement password strength & complexity checking
  powerdnsadmin/models/setting.py
  powerdnsadmin/routes/admin.py
  powerdnsadmin/routes/index.py
  powerdnsadmin/routes/user.py
  powerdnsadmin/templates/admin_setting_authentication.html
  powerdnsadmin/templates/user_profile.html
  requirements.txt
Labels: mod / accepted, mod / reviewed

#1238 Fix LDAP user group search for nested groups
  powerdnsadmin/models/user.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1461 Fix manual session clearing that triggered session expiration bug
  powerdnsadmin/routes/index.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1463 Fix LDAP group restrictions by allowing the use of any combination of groups.
  powerdnsadmin/models/user.py
  powerdnsadmin/templates/admin_setting_authentication.html
Labels: mod / accepted, mod / reviewed, feature / update

#1479 Improve exception handling for invalid UTF-8 encoded X-API-KEY header
  powerdnsadmin/decorators.py
Labels: bug / broken-feature, mod / accepted, mod / reviewed

#1481 Fix activity search invalid form markup causing submission failures
  powerdnsadmin/templates/admin_history.html
Labels: bug / broken-feature, mod / accepted, mod / reviewed
